name: Daily Birthday Email Cron


on:
  schedule:
    - cron: "0 6 * * *"  # every day at 6:00 UTC
  workflow_dispatch:  # allows manual triggering

jobs:
  run-worker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0 
      - name: Install dependencies
        run: npm install

      - name: Run worker.js
        run: node worker.js
        env:
          DB_URI: ${{ secrets.DB_URI }}          
          MAIL_USER: ${{ secrets.GMAIL_USER }}   
          MAIL_PASS: ${{ secrets.GMAIL_PASS }}   
